config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  devise_for :cashiers, :skip => [:registrations]
  devise_for :admins
  resources :cashiers
  resources :products
  resources :orders
  resources :order_lines
  get 'homepage/index'
  post 'order_line/new'
  root 'homepage#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :cashier
  has_many :order_lines
  attr_accessor :total_price, :cash, :cashier, :order_line_attributes
  accepts_nested_attributes_for :order_lines, 
                                allow_destroy: true,
                                :reject_if => :all_blank
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :authenticate_admin!, only: [:new, :edit, :update, :create, :destroy, :index, :show]
    def new
        @order = Order.new
    end
    def edit
    end
    def update
    end
    def create
        @order = Order.new(params[:order].permit(:cashier_id, :total_price, :cash))
        @order.save
        redirect_to @order
    end
    def index
        @orders = Order.all
    end
    def destroy
        @order = Order.find(params[:id])
        @order.destroy
        redirect_to controller: 'orders'
    end
    def show
        @order = Order.find(params[:id])
    end
    private
    def order_params
        params.require(:order).permit(:cashier_id, :total_price, :cash)
    end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/orders/_new_product.html.erb
<%= simple_form_for(:products) do |f| %>
<tr class="nested-fields">
  <td><%= f.collection_select :order_line_id, Product.all, :id, :name %></td>
  <td><%= f.input :quantity, label: false %></td>
  <td><%= f.input :price, label: false %></td>
</tr>
<% end %>

app/views/orders/_order_line_fields.html.erb
    <tr class="nested-fields">
        <td><%= f.collection_select :product_id, Product.all, :id, :name, :prompt => true %></td>
        <td><%= f.input :quantity, label: false %></td>
    </tr>

app/views/orders/backupnew.erb
<h1>Order Summary</h1>
<% total = 0.0 %>
<% @order_lines.each do |order_line| %>
    <tr>
      <td><%= Product.find(order_line.product_id_id).name %></td>
      <td><%= order_line.quantity %></td>
      <td><%= order_line.price %></td>
    </tr>
    <% total += (order_line.quantity * order_line.price)%>
<% end %>
<p>
    Total Price: <%= total %>
</p>
<%= form_for @order, :url => {:controller => "order"} do |i| %>
    <p>
        <%= i.label :cash %><br>
        <%= i.text_field :cash %>
    </p>
    <% @order.total_price = total %>
    <%= i.hidden_field :total_price, value: total %>
    <%= i.submit %>
<% end %>

app/views/orders/index.html.erb
<style>
  h1{
        color: black;
        font-family: 'Trebuchet MS', Helvetica, sans-serif; 
        font-size: 65px; 
        font-weight: normal; 
        line-height: 60px; 
        margin: 10px 0 20px; 
        text-transform: uppercase; 
        text-shadow: 2px 2px 0 #000, margin: 10px 0 24px; 
        text-align: center;
  }
  
  #links{
        text-align: center;
  }
  
  #table{
      color: #333333; 
      font-family: 'Muli', sans-serif; 
      font-size: 18px; 
      line-height: 28px; 
      margin: 0 0 28px;
    }
</style>

<h1>Orders</h1>
<div id = "links">
<%= link_to 'Home', '/', class: 'btn btn-primary' %>
<!-- '/' refers to the home page-->
<%= link_to 'New Order', new_order_path, class: 'btn btn-success' %>
</div>
<table class="table table-striped">
    <tr>
        <th>Cashier</th>
        <th>Total Price</th>
        <th>Cash</th>
        <th colspan="3"></th>
    </tr>
    <% @orders.each do |order| %>
        <tr>
          <td><%= order.cashier_id %></td>
          <td><%= order.total_price %></td>
          <td><%= order.cash %></td>
          <td><%= button_to 'Remove', order_path(order),
              method: :delete,
              class: 'btn btn-danger' %></td>
        </tr>
    <% end %>
</table>

app/views/orders/new.html.erb
<h1>New Order</h1>
<%= simple_form_for @order do |f| %>
<%= f.error_notification %>
  <h3>Tasks</h3>
  <table class='table'>
    <thead>
      <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
    </thead> 
    <tbody>
    <%= f.simple_fields_for :order_lines do |ol| %>
      <%= render 'order_line_fields', f: ol %>
    <% end %>
    </tbody>
  </table>
  <div class="form-actions">
    <%= link_to_add_association 'Add Product', f, :order_lines, class: 'btn btn-primary'%>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/orders/show.html.erb
    <%= debug @order %>