config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  devise_for :cashiers, :skip => [:registrations]
  devise_for :admins
  resources :cashiers
  resources :products
  resources :orders
  resources :order_lines
  get 'homepage/index'
  post 'order_line/new'
  root 'homepage#index'

end

app/models/cashier.rb
class Cashier < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :admin
  has_many :orders
end

app/controllers/cashiers_controller.rb
class CashiersController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :edit, :update, :create, :destroy, :index, :show]
  def new
  end
  def create
    @cashier = Cashier.new(params[:cashier].permit(:email, :name, :password, :status))
    @cashier.password = :password
    @cashier.status = true
    @cashier.save
    redirect_to @cashier
  end
  def edit
    @cashier = Cashier.find(params[:id])
  end
  def update
    # go to edit.html.erb, do some stuff with instance @product, bring them here then do "@product.update"
    # ".update" is a built-in Rails function
    @cashier = Cashier.find(params[:id])
    if @cashier.update(cashier_params)
      redirect_to @cashier
    else
      render 'edit'
    end
  end
  def destroy
    @cashier = Cashier.find(params[:id])
    @cashier.destroy
    redirect_to cashiers_path
  end
  def show
    @cashier = Cashier.find(params[:id])
  end
  def index
    @cashiers = Cashier.all
  end
  private
    def cashier_params
        params.require(:cashier).permit(:name, :email, :encrypted_password, :status)
    end
end

app/helpers/cashiers_helper.rb
module CashiersHelper
end

app/views/cashiers/edit.html.erb
<style>
        h1{
        color: black;
        font-family: 'Trebuchet MS', Helvetica, sans-serif; 
        font-size: 65px; 
        font-weight: normal; 
        line-height: 60px; 
        margin: 10px 0 20px; 
        text-transform: uppercase; 
        text-shadow: 2px 2px 0 #000, margin: 10px 0 24px; 
        text-align: center;
    }
    
    #content{
        color: #333333; 
        font-family: 'Muli', sans-serif; 
        font-size: 18px; 
        line-height: 28px; 
        margin: 0 0 28px;
        text-align: center;
    }
    #content2
    {
        text-align:center;
    }
</style>

<h1>Edit Cashier</h1>

<div id="content">
<%= form_for (@cashier) do |i| %>
    <p>
        <%= i.label :name %>
        <%= i.text_field :name %>
    </p>
    <p>
        <%= i.label :email %>
        <%= i.email_field :email %>
    </p>
    <p>
        <%= i.label :status %>
        <%= i.text_field :status %>
    </p>
</div>

<div id="content2">
    <p>
        <%= i.submit %>
    </p>
<% end %>
<%= link_to 'Back', cashiers_path, class: 'btn btn-primary btn-sm' %>
</div>

app/views/cashiers/index.html.erb
<style>
  h1{
        color: black;
        font-family: 'Trebuchet MS', Helvetica, sans-serif; 
        font-size: 65px; 
        font-weight: normal; 
        line-height: 60px; 
        margin: 10px 0 20px; 
        text-transform: uppercase; 
        text-shadow: 2px 2px 0 #000, margin: 10px 0 24px; 
        text-align: center;
  }
  
  #links{
        text-align: center;
  }
  
  #table{
      color: #333333; 
      font-family: 'Muli', sans-serif; 
      font-size: 18px; 
      line-height: 28px; 
      margin: 0 0 28px;
    }
</style>

<h1>Cashiers</h1>
<div id = "links">
  <%= link_to 'Home', '/', class: 'btn btn-primary' %>
  <!-- '/' refers to the home page-->
  <%= link_to 'New Cashier', new_cashier_path, class: 'btn btn-success' %>
  <!-- ^^^links to new.html.erb from the products controller -->
</div>

<div id = "table">
<table class="table table-striped">
  <tr>
    <th>Email</th>
    <th>Name</th>
    <th>Availability</th>
    <th colspan="3"></th>
  </tr>
 
  <% @cashiers.each do |cashier| %>
    <tr>
      <td><%= cashier.email %></td>
      <td><%= cashier.name %></td>
      <!--<td><%= cashier.status %></td>-->
      <td>
      <% if cashier.status == true %>
        <%= 'Active' %>
      <% else %>
        <%= 'Inactive' %>
      <%end%>
      </td>
      <td><%= link_to 'View', cashier_path(cashier), class: 'btn btn-primary' %></td>
      <td><%= link_to 'Edit', edit_cashier_path(cashier), class: 'btn btn-info' %></td>
      <!--should it be product.id or nah-->
      <td><%= button_to 'Remove', cashier_path(cashier),
              method: :delete,
              class: 'btn btn-danger' %></td>
      <!-- Destroy has been temporarily fixed by switching link_to with button_to -->
      <!-- "(product)" refers to the product in question from @products.each-->
      <td colspan="2"></td>
    </tr>
  <% end %>
</table>
</div>

app/views/cashiers/new.html.erb
<style>
    h1{
        color: black;
        font-family: 'Trebuchet MS', Helvetica, sans-serif; 
        font-size: 65px; 
        font-weight: normal; 
        line-height: 60px; 
        margin: 10px 0 20px; 
        text-transform: uppercase; 
        text-shadow: 2px 2px 0 #000, margin: 10px 0 24px; 
        text-align: center;
    }
    
    #content{
        color: #333333; 
        font-family: 'Muli', sans-serif; 
        font-size: 18px; 
        line-height: 28px; 
        margin: 0 0 28px;
        text-align: center;
    }
    #content2
    {
        text-align:center;
    }
</style>

<h1>Create a New Cashier!</h1>

<div id ="content">
<%= form_for :cashier, url: cashiers_path do |i| %>
    <p>
        <%= i.label :name %><br>
        <%= i.text_field :name %>
    </p>
    <p>
        <%= i.label :email %><br>
        <%= i.email_field :email %>
    </p>
    <p>
        <%= i.label :password %><br>
        <%= i.password_field :password %>
    </p>
    <p>
        <%= i.label :password_confirmation %><br>
        <%= i.password_field :password_confirmation %>
    </p>
</div>
    
<div id = "content2">
    <p>
        <%= i.submit %>
    </p>
<% end %>
      <%= link_to 'Back', cashiers_path, class: 'btn btn-primary btn-sm' %>
      
</div>
  

app/views/cashiers/show.html.erb
<style>
    h1 {
        color: black;
        font-family: 'Trebuchet MS', Helvetica, sans-serif; 
        font-size: 65px; 
        font-weight: normal; 
        line-height: 60px; 
        margin: 10px 0 20px; 
        text-transform: uppercase; 
        text-shadow: 2px 2px 0 #000, margin: 10px 0 24px; 
        text-align: center;
    }
    
    #content{
        color: #333333; 
        font-family: 'Muli', sans-serif; 
        font-size: 18px; 
        line-height: 28px; 
        margin: 0 0 28px;
    }
    #content{
        text-align: justify;
        margin: 0 auto;
        width: 20em;
    }
    #content2{
        text-align: center;
    }
    
</style>
<h1>Cashier Information</h1>
<div id = "content">
<p>
    <strong>Cashier Name: </strong><%= @cashier.name %>
</p>
<p>
    <strong>Cashier Email: </strong><%= @cashier.email %>
</p>
<p>
    <strong>Cashier Availability: </strong>
<!--    <%= @cashier.status %>-->
    <% if @cashier.status==true %>
        <%= 'Active' %>
    <% else %>
        <%= 'Inactive' %>
    <%end%>
</p>
</div>

<div id = "content2">
<%= link_to 'Edit', edit_cashier_path(@cashier), class: 'btn btn-success btn-sm' %>
<%= link_to 'Back', cashiers_path, class: 'btn btn-primary btn-sm' %>
</div>