config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  devise_for :cashiers, :skip => [:registrations]
  devise_for :admins
  resources :cashiers
  resources :products
  resources :orders
  resources :order_lines
  get 'homepage/index'
  post 'order_line/new'
  root 'homepage#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
    belongs_to :admin
    belongs_to :order_line
    accepts_nested_attributes_for :order_line
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_admin!, only: [:new, :edit, :update, :create, :destroy, :index, :show]
    # ^^^ means that only an authenticated admin can do the following command
    layout "application"
    def new
    end
    def edit
        @product = Product.find(params[:id])
    end
    def update
        # go to edit.html.erb, do some stuff with instance @product, bring them here then do "@product.update"
        # ".update" is a built-in Rails function
        @product = Product.find(params[:id])
        if @product.update(product_params)
            redirect_to @product
        else
            render 'edit'
        end
    end
    def create
        #render plain: params[:product].inspect
        #^^^ this just prints the stuff from the "new" form
        @product = Product.new(params[:product].permit(:name, :price, :status))
        #^^^ ".permit" is related to Rails' security stuff, this allows the app to permit its own attributes
        @product.status = true
        #^^^ status is a paremeter made with the Product model, it's set to true because we want the product to be available immediately
        @product.save
        #^^^ ".save" saves the model to the database
        redirect_to @product
    end
    def destroy
        @product = Product.find(params[:id])
        @product.destroy
        redirect_to products_path
    end
    def show
        @product = Product.find(params[:id])
        #^^^ "params[:id] is there to find the Product with an id that the app is interested in"
    end
    def index
        @products = Product.all
        #^^^ the code to list all product, it is very important that the "@" variable is PLURAL
    end
    private
        def product_params
            params.require(:product).permit(:name, :price, :status)
        end
end

#new and create are built-in on Rails, they exist automatically via "rails generate"
#the built-in commands always refer to their respective html files: "<controller name>/<new/ create/ etc,>.html.erb"
# ex: "new" on a Products Controller refers to the new.html.erb on views/products

#Rails models are automatically initialized with its attributes

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<style>
        h1{
        color: black;
        font-family: 'Trebuchet MS', Helvetica, sans-serif; 
        font-size: 65px; 
        font-weight: normal; 
        line-height: 60px; 
        margin: 10px 0 20px; 
        text-transform: uppercase; 
        text-shadow: 2px 2px 0 #000, margin: 10px 0 24px; 
        text-align: center;
    }
    
    #content{
        color: #333333; 
        font-family: 'Muli', sans-serif; 
        font-size: 18px; 
        line-height: 28px; 
        margin: 0 0 28px;
        text-align: center;
    }
    #content2
    {
        text-align:center;
    }
</style>

<h1>Edit Product</h1>

<div id="content">
<%= form_for (@product) do |i| %>
    <p>
        <%= i.label :name %>
        <%= i.text_field :name %>
    </p>
    <p>
        <%= i.label :price %>
        <%= i.text_field :price %>
    </p>
    <p>
        <%= i.label :status %>
        <%= i.text_field :status %>
    </p>
</div>
<div id="content2">
    <p>
        <%= i.submit %>
    </p>
<% end %>
<%= link_to 'Back', products_path, class: 'btn btn-primary btn-sm' %>
</div>

app/views/products/index.html.erb
<style>
  h1{
        color: black;
        font-family: 'Trebuchet MS', Helvetica, sans-serif; 
        font-size: 65px; 
        font-weight: normal; 
        line-height: 60px; 
        margin: 10px 0 20px; 
        text-transform: uppercase; 
        text-shadow: 2px 2px 0 #000, margin: 10px 0 24px; 
        text-align: center;
  }
  
  #links{
        text-align: center;
  }
  
  #table{
      color: #333333; 
      font-family: 'Muli', sans-serif; 
      font-size: 18px; 
      line-height: 28px; 
      margin: 0 0 28px;
    }
</style>

<h1>Product List</h1>
<div id = "links">
<%= link_to 'Home', '/', class: 'btn btn-primary' %>
<!-- '/' refers to the home page-->
<%= link_to 'New Product', new_product_path, class: 'btn btn-success' %>
<!-- ^^^links to new.html.erb from the products controller -->
</div>
<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Availability</th>
    <th colspan="3"></th>
  </tr>
 
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <td><!--<%= product.status %>-->
      <% if product.status==true %>
        <%= 'Available' %>
      <% else %>
        <%= 'Unavailable' %>
      <%end%></td>
      <td><%= link_to 'View', product_path(product), class: 'btn btn-primary' %></td>
      <td><%= link_to 'Edit', edit_product_path(product), class: 'btn btn-info' %></td>
      <!--should it be product.id or nah-->
      <td><%= button_to 'Remove', product_path(product),
              method: :delete,
              class: 'btn btn-danger' %></td>
      <!-- Destroy has been temporarily fixed by switching link_to with button_to -->
      <!-- "(product)" refers to the product in question from @products.each-->
      <td colspan="2"></td>
    </tr>
  <% end %>
</table>

app/views/products/new.html.erb
<style>
    h1{
        color: black;
        font-family: 'Trebuchet MS', Helvetica, sans-serif; 
        font-size: 65px; 
        font-weight: normal; 
        line-height: 60px; 
        margin: 10px 0 20px; 
        text-transform: uppercase; 
        text-shadow: 2px 2px 0 #000, margin: 10px 0 24px; 
        text-align: center;
    }
    
    #content{
        color: #333333; 
        font-family: 'Muli', sans-serif; 
        font-size: 18px; 
        line-height: 28px; 
        margin: 0 0 28px;
        text-align: center;
    }
    #content2
    {
        text-align:center;
    }
</style>

<h1>Create a New Product!</h1>
<div id ="content">
<%= form_for :product, url: products_path do |i| %>
    <p>
        <%= i.label :name %><br>
        <%= i.text_field :name %>
    </p>
    <p>
        <%= i.label :price %><br>
        <%= i.text_field :price%>
    </p>
</div>
<div id = "content2">    
    <p>
        <%= i.submit %>
    </p>
<% end %>
<%= link_to 'Back', products_path, class: 'btn btn-primary btn-sm' %>
</div>
<!-- ^^ links back to the "/products" path, which refers to the Controller's index"-->

<!-- form_for is built-in with Rails
same with .label, .text_field and .submit-->

app/views/products/show.html.erb
<style>
    h1 {
        color: black;
        font-family: 'Trebuchet MS', Helvetica, sans-serif; 
        font-size: 65px; 
        font-weight: normal; 
        line-height: 60px; 
        margin: 10px 0 20px; 
        text-transform: uppercase; 
        text-shadow: 2px 2px 0 #000, margin: 10px 0 24px; 
        text-align: center;
    }
    
    #content{
        color: #333333; 
        font-family: 'Muli', sans-serif; 
        font-size: 18px; 
        line-height: 28px; 
        margin: 0 0 28px;
    }
    #content{
        text-align: justify;
        margin: 0 auto;
        width: 20em;
    }
    #content2{
        text-align: center;
    }
</style>
<h1>Product Information</h1>
<div id = "content">
<p>
    <strong>Product Name: </strong><%= @product.name %>
</p>
<p>
    <strong>Product Price: </strong><%= @product.price %>
</p>
<p>
    <strong>Product Availability: </strong><!--<%= @product.status %>-->
    <% if @product.status==true %>
        <%= 'Available' %>
    <% else %>
        <%= 'Unavailable' %>
    <%end%>
</p>
</div>
<div id = "content2">
<%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-success btn-sm' %>
<%= link_to 'Back', products_path, class: 'btn btn-primary btn-sm' %>
</div>