config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  devise_for :cashiers, :skip => [:registrations]
  devise_for :admins
  resources :cashiers
  resources :products
  resources :orders
  resources :order_lines
  get 'homepage/index'
  post 'order_line/new'
  root 'homepage#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
</head>
  <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">POS System</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <% if admin_signed_in? %>
                  <li>
                    <%= link_to "Products", products_path %>
                  </li>
                  <li>
                    <%= link_to "Cashiers", cashiers_path %>
                  </li>
                  <li>
                    <%= link_to "Orders", orders_path %>
                  </li>
                <% end %>
              </ul>
          
              <p class="navbar-text pull-right">
                <% if admin_signed_in? %>
                  Logged in as <strong><%= current_admin.email %></strong>.
                  <%# link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> 
                  <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
                <% else %>
                  <%# link_to "Sign up", new_admin_registration_path, :class => 'navbar-link'  %> 
                  <%# link_to "Login", new_admin_session_path, :class => 'navbar-link'  %>
                <% end %>
              </p>
            </div>
          </div>
        </nav>

    <div class="container">

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      
      <%= yield %>
    </div>
    
  </body>
</html>